### ISSUE TITLE
Coda jumps to top when clicking near the bottom of a dataset

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/CodaV2#170] opened 2018-12-12 10:38 UTC
When I open a dataset with enough rows to scroll, scroll to the bottom, then click on one of the rows near the bottom, Coda jumps all the way back to the top of the page. This only happens with message text, not the drop-down selectors.

**Comment by lukechurch** [comment] 2018-12-15 16:51
Only reproduced in Safari, can't reproduce in Chrome. As our user population is mainly Windows and Linux, marking as low priority.

(@as2388 if this is seriously disrupting a workflow you need, let's discuss)

**Comment by lukechurch** [comment] 2019-02-02 17:31
Safari isn't supported for now. If we decide to support other browsers we'll need to do a bunch of systematic testing

**Closed by lukechurch** 2019-02-02 17:31 UTC
